Photo.create!([
  {title: "Pinecones?", description: "LOOK AT ALL THESE PINECONES\n\n", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506907/wmmx2oytrz9jwmet3of9.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506907/wmmx2oytrz9jwmet3of9.jpg", albuming_id: nil, filters: nil},
  {title: "rock'n'water", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506888/ykqqkl5b9lpcg7f1p123.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506888/ykqqkl5b9lpcg7f1p123.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506899/ryvjpmi2jdoebe3iplem.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506899/ryvjpmi2jdoebe3iplem.jpg", albuming_id: nil, filters: nil},
  {title: "orange suns", description: "ffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfadsffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsf\nsdffasd\ndasf\nsd\nf\nsadf\nadsf", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506875/yxfllichvbv8jugyzjun.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506875/yxfllichvbv8jugyzjun.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567961/cssobc2vv70018maceaq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567961/cssobc2vv70018maceaq.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568036/zr5tzul9vzw9qvetdpmr.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568036/zr5tzul9vzw9qvetdpmr.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568056/ducry4tleg8cfu8kex5d.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568056/ducry4tleg8cfu8kex5d.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568087/utklb2jvbzrv2h7yqfu8.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568087/utklb2jvbzrv2h7yqfu8.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568237/odfrapicgjbhb0zhwljz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568237/odfrapicgjbhb0zhwljz.jpg", albuming_id: nil, filters: nil},
  {title: "Water and Rocks", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568278/xy6asygjymlq9lz5wgw3.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568278/xy6asygjymlq9lz5wgw3.jpg", albuming_id: nil, filters: nil},
  {title: "clouds", description: "I think I can see a mountain too", user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568270/ms1ongsmyamdlfhinnrq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568270/ms1ongsmyamdlfhinnrq.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573475/is6kkgv0orro0lccovcw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573475/is6kkgv0orro0lccovcw.jpg", albuming_id: nil, filters: nil},
  {title: "Orange and Blue", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568248/o4qderewgojwvrmcpqkg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568248/o4qderewgojwvrmcpqkg.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573489/gtzvqznidaqc2yawlk8m.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573489/gtzvqznidaqc2yawlk8m.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506919/yak37eq3lovk5fbkn1lk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506919/yak37eq3lovk5fbkn1lk.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567919/rr9mm2o6q5cijgvakkto.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567919/rr9mm2o6q5cijgvakkto.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568077/bl3vqs2uuprcz75n3zws.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568077/bl3vqs2uuprcz75n3zws.jpg", albuming_id: nil, filters: nil},
  {title: "Looks dangerous", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567885/ulatmcr1kywbu8xgo0sy.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567885/ulatmcr1kywbu8xgo0sy.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "la la lalalala", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567834/lvxofvho8isvepume05z.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567834/lvxofvho8isvepume05z.jpg", albuming_id: nil, filters: nil},
  {title: "Fall", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567861/l1ncijpv7sn0zrordllc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567861/l1ncijpv7sn0zrordllc.jpg", albuming_id: nil, filters: nil},
  {title: "Majestic Alcoholism", description: "sadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efj", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg", albuming_id: nil, filters: nil},
  {title: "title", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567844/svpzafqwropjoi15izpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567844/svpzafqwropjoi15izpa.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "\n\n\n\n\n\n\n\n\n", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567910/f1vzfg466cxtajwseabi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567910/f1vzfg466cxtajwseabi.jpg", albuming_id: nil, filters: nil},
  {title: "Green door", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567997/dypwznqr7fvfj78npmlx.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567997/dypwznqr7fvfj78npmlx.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "sdfasdf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568101/vki57g6ymn0jarzvrpec.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568101/vki57g6ymn0jarzvrpec.jpg", albuming_id: nil, filters: nil},
  {title: "sadf", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567901/ll0eautrhzidevgj26xi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567901/ll0eautrhzidevgj26xi.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568024/avooyw2bbeu3lrdftmjw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568024/avooyw2bbeu3lrdftmjw.jpg", albuming_id: nil, filters: nil},
  {title: "beans", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567949/wueevxjcfhauuumyfptl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567949/wueevxjcfhauuumyfptl.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567892/c368dobi8dr0u27mgbv1.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567892/c368dobi8dr0u27mgbv1.jpg", albuming_id: nil, filters: nil},
  {title: "lotta tan in this one", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567932/nd3hexzkdorjn7eieawk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567932/nd3hexzkdorjn7eieawk.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568069/gtpham7dmmlwqlzobnqc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568069/gtpham7dmmlwqlzobnqc.jpg", albuming_id: nil, filters: nil},
  {title: "dsaf", description: "fdsaf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567941/srm6g452ouksm2mumm21.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567941/srm6g452ouksm2mumm21.jpg", albuming_id: nil, filters: nil},
  {title: "telebooth", description: "a booth in the glow of night", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567975/nsqubkstwvcchrskrbpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567975/nsqubkstwvcchrskrbpa.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573497/zpi6hkmyzcymqf9jncuf.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573497/zpi6hkmyzcymqf9jncuf.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573514/ysuovu1a1zti7ihmdght.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573514/ysuovu1a1zti7ihmdght.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573525/ub1ki1j7gol3hprbrjil.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573525/ub1ki1j7gol3hprbrjil.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573537/pdghysdo5pw7w3k6vc8n.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573537/pdghysdo5pw7w3k6vc8n.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573588/eb1tywyi75penp8wpxvl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573588/eb1tywyi75penp8wpxvl.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573596/gpby0lpg0ye1blo7swi2.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573596/gpby0lpg0ye1blo7swi2.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573603/kn5wvqby9agcei0zdf7q.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573603/kn5wvqby9agcei0zdf7q.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573610/leafneiwhzjt3fvgwtpt.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573610/leafneiwhzjt3fvgwtpt.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573616/igmmo21gfwskhpq15k4s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573616/igmmo21gfwskhpq15k4s.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573624/thy8geqji8zbgzoui0vu.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573624/thy8geqji8zbgzoui0vu.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573635/mcznlokr7uoyxvu3k22f.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573635/mcznlokr7uoyxvu3k22f.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573659/pae3qn6ccqcqg0tqqsol.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573659/pae3qn6ccqcqg0tqqsol.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573673/ippwqlanpolrrgrkobev.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573673/ippwqlanpolrrgrkobev.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573703/gps7xunnmxodtof5xtds.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573703/gps7xunnmxodtof5xtds.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567825/hbssjxxwoffneuedeysp.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567825/hbssjxxwoffneuedeysp.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 6, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439597776/iomxelfkvjzoilrd0gxg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439597776/iomxelfkvjzoilrd0gxg.jpg", albuming_id: nil, filters: nil},
  {title: "wow", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704558/chhcdlqqatqvqtdgxqaj.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704558/chhcdlqqatqvqtdgxqaj.jpg", albuming_id: nil, filters: nil},
  {title: "I'm getting dizzy", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439739084/yfrypm7cgvh9cd2h82og.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439739084/yfrypm7cgvh9cd2h82og.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704520/tdqh0j1gm0alz6eei8kq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704520/tdqh0j1gm0alz6eei8kq.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704574/yf7btz05nl7lubjf5xmi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704574/yf7btz05nl7lubjf5xmi.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738328/enc058emzzpbu8fre0nh.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738328/enc058emzzpbu8fre0nh.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738386/myr5w9imlerideugcnj0.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738386/myr5w9imlerideugcnj0.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738668/xiakkntdydqbntyal52f.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738668/xiakkntdydqbntyal52f.jpg", albuming_id: nil, filters: nil},
  {title: "what a good book!", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704542/vkr58kvpf988lgplkdxz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704542/vkr58kvpf988lgplkdxz.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786041/ovavwg7x95tfszdcctjz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786041/ovavwg7x95tfszdcctjz.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786409/ichxszoarur7wdzmu6cx.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786409/ichxszoarur7wdzmu6cx.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439789405/ch1o3v2iwdrmrqshxu2m.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439789405/ch1o3v2iwdrmrqshxu2m.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568069/gtpham7dmmlwqlzobnqc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568069/gtpham7dmmlwqlzobnqc.jpg", albuming_id: nil, filters: "{\"bl\":1,\"br\":82,\"co\":200,\"gr\":44,\"hu\":315,\"iv\":0,\"sa\":100,\"se\":0}"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1440032536/jposxhrrldo7hfnc07jl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1440032536/jposxhrrldo7hfnc07jl.jpg", albuming_id: nil, filters: "{\"bl\":0,\"br\":139,\"co\":100,\"gr\":0,\"hu\":4,\"iv\":0,\"sa\":100,\"se\":70}"},
  {title: ":(", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786899/ijzxbxh0ahkf3atyypbw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786899/ijzxbxh0ahkf3atyypbw.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "white water rafting yo", user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439787412/u0yqdoemoly5ah0ijg1j.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439787412/u0yqdoemoly5ah0ijg1j.jpg", albuming_id: nil, filters: nil},
  {title: "island paradise", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1440032536/jposxhrrldo7hfnc07jl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1440032536/jposxhrrldo7hfnc07jl.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439787363/bddc59vjalhxpwpoppzy.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439787363/bddc59vjalhxpwpoppzy.jpg", albuming_id: nil, filters: "{\"bl\":0,\"br\":100,\"co\":100,\"gr\":0,\"hu\":0,\"iv\":0,\"sa\":100,\"se\":0}"}
])

User.create!([
  {username: "guest", password_digest: "$2a$10$dHHLYl8fA/6hLHt/xaAh6eOQ9JRCE7N2J9XQpP6yjZ3hMcLrQfd5m", session_token: "MVEyHWhC9W_gH9_89h1J1w"},
  {username: "pointlessComments", password_digest: "$2a$10$d4Y9l6EVq0ct0VYywJstseTyUR8fOvwB.xSxl6ks1Uuci1DNJNyQe", session_token: "IOOmbticQ3M5e0zknA9ldw"},
  {username: "i_love_pictur", password_digest: "$2a$10$WI5kuxQ0tXS9Si2vHYrW.enpoXVtkxP/j91yxCpr.km51EuW5iNtO", session_token: "rseP2ZfOyXou9UhV7TgGjQ"},
  {username: "photo4lyfe", password_digest: "$2a$10$IJu8GpoGrG5kr8b88yKxm.0blFSV3wLeIq2Dxue/5BBS//anIvxaC", session_token: "evXk6caoTEgl8RtBrH5qkA"},
  {username: "anewuser", password_digest: "$2a$10$bsT3Szp212hhcAMa.8PNX.avY3bWGvuNlIzigozGNEkRRM7W.NGw6", session_token: "vgtnG2GkfdsMI1ISHKi_fw"},
  {username: "joe_smith", password_digest: "$2a$10$Y5kConGq8nFsimVYe9XTAunmxdK2Htetpctz8iAnUa0/FPIE6kyyq", session_token: "aQPljq6hsHunAGiCBEXhvg"},
  {username: "tad", password_digest: "$2a$10$fUGJM1ZkRi61qZDpGRjmEeVEsZeIulEtF13F1OE1Z25HTz4tGJ4d2", session_token: "PbxUEg3OcH5bV3YsyPsOZg"},
  {username: "inactive_user", password_digest: "$2a$10$j6EtiYgaAYYDralGUnIsguTiHMpGiEka28xRyfNdD4z3Br/em0D9a", session_token: "Xj2kXWeLvdKWJwJY_Y9VGQ"}
])

User.all.each do |user|
  30.times do
    Photo.find(rand(68) + 1).comments.create!(
      body: (rand(2) == 0 ? Faker::Lorem.paragraph(rand(10) + 1) : Faker::Lorem.sentence(rand(10) + 1)),
      user_id: user.id
    )
  end

  30.times do
    user.votings.create({ user_id: user.id, photo_id: rand(68) + 1, score: 1 })
  end

  3.times do
    a = user.albums.create({ name: Faker::Commerce.product_name })
    user.photos.each do |photo|
      if rand(2) == 0
        photo.albumings.create({ album_id: a.id, photo_id: photo.id })
      end
    end
  end
end
