Album.create!([
  {name: "new album", user_id: 7},
  {name: "the 2nd comming of album", user_id: 7},
  {name: "the whole shabang", user_id: 7},
  {name: "my awesome album", user_id: 1}
])
Albuming.create!([
  {album_id: 1, photo_id: 66},
  {album_id: 1, photo_id: 91},
  {album_id: 1, photo_id: 69},
  {album_id: 1, photo_id: 98},
  {album_id: 7, photo_id: 64},
  {album_id: 7, photo_id: 54},
  {album_id: 7, photo_id: 59},
  {album_id: 4, photo_id: 43},
  {album_id: 4, photo_id: 44},
  {album_id: 4, photo_id: 45},
  {album_id: 4, photo_id: 46},
  {album_id: 4, photo_id: 47},
  {album_id: 4, photo_id: 49},
  {album_id: 4, photo_id: 34},
  {album_id: 4, photo_id: 51},
  {album_id: 4, photo_id: 70},
  {album_id: 4, photo_id: 41},
  {album_id: 4, photo_id: 29},
  {album_id: 4, photo_id: 23},
  {album_id: 4, photo_id: 99},
  {album_id: 4, photo_id: 28},
  {album_id: 4, photo_id: 32},
  {album_id: 4, photo_id: 31},
  {album_id: 2, photo_id: 59},
  {album_id: 2, photo_id: 54},
  {album_id: 2, photo_id: 68},
  {album_id: 2, photo_id: 91},
  {album_id: 2, photo_id: 58},
  {album_id: 3, photo_id: 60},
  {album_id: 3, photo_id: 54},
  {album_id: 3, photo_id: 64},
  {album_id: 3, photo_id: 66},
  {album_id: 3, photo_id: 67},
  {album_id: 3, photo_id: 69},
  {album_id: 3, photo_id: 91},
  {album_id: 3, photo_id: 68}
])
Comment.create!([
  {body: "this is a long comment so I can see hwo long a comment is to see how much space it takes up to know how to style the page so as to fit all the content but also look decent where there is not a lot of content", photo_id: 49, user_id: 1},
  {body: "test comment 1", photo_id: 49, user_id: 1},
  {body: "Id repellendus pariatur sequi enim id error doloremque aperiam ex.", photo_id: 12, user_id: 5},
  {body: "Totam quod eum reprehenderit incidunt dolores nostrum aut culpa.", photo_id: 7, user_id: 5},
  {body: "Consectetur enim exercitationem incidunt quia inventore eius excepturi quo temporibus dolor repellat nihil adipisci repudiandae.", photo_id: 12, user_id: 4},
  {body: "Ut iusto quos.", photo_id: 20, user_id: 2},
  {body: "Maiores vero temporibus quia quas necessitatibus corporis. Velit suscipit aut dignissimos. Aperiam autem velit. Voluptatem ad eligendi dolores natus voluptatibus. Tempora animi et sequi aut minima pariatur amet. Delectus deserunt veniam commodi alias labore quam soluta. Ducimus corporis nostrum similique hic placeat. Nostrum sapiente impedit sed aut.", photo_id: 14, user_id: 6},
  {body: "Impedit rerum culpa rem explicabo est dolores voluptatibus eum mollitia possimus illo repellat.", photo_id: 11, user_id: 1},
  {body: "Numquam minima eveniet dolor velit. Autem asperiores quo maiores alias necessitatibus saepe. Exercitationem ullam quod consequatur. Dolorem iusto dolorum suscipit soluta aut maiores. Dignissimos quod repellendus voluptas eveniet et provident. Odit id praesentium consequatur et eius.", photo_id: 16, user_id: 2},
  {body: "Error molestias a voluptatem ducimus.", photo_id: 9, user_id: 2},
  {body: "Voluptatibus veniam iure aut est corrupti eaque omnis non tempora velit.", photo_id: 9, user_id: 6},
  {body: "Ducimus perspiciatis expedita voluptatum magni cumque voluptatibus explicabo veniam.", photo_id: 19, user_id: 4},
  {body: "Aliquid quos enim.", photo_id: 5, user_id: 6},
  {body: "Temporibus perspiciatis maiores aliquid sunt ea vel. Deleniti molestias illo qui laboriosam totam voluptate. Ea doloribus inventore qui. Fugit facilis nihil quaerat aut sunt labore. Neque cumque et ad vitae natus nulla.", photo_id: 18, user_id: 6},
  {body: "Qui quaerat ut. Earum quaerat quam mollitia molestiae dolorum recusandae. Dolore consequatur consequatur provident.", photo_id: 9, user_id: 5},
  {body: "Impedit ullam fugiat et aperiam et rerum ut. Eos enim molestias repellat voluptatibus. Autem aut voluptatem eveniet iste ut eum. Earum nulla accusamus reprehenderit perspiciatis. Porro eum quidem dicta. Est officia quidem. Minima nesciunt maiores. Facere et totam quibusdam quisquam fugiat placeat nihil. Harum neque non.", photo_id: 5, user_id: 1},
  {body: "Laboriosam veniam vel dignissimos enim in et iusto magni exercitationem dolor quisquam.", photo_id: 19, user_id: 1},
  {body: "Quae aspernatur et atque animi. Architecto harum ea eligendi. Qui neque exercitationem qui quia et qui.", photo_id: 8, user_id: 3},
  {body: "Minus aut reprehenderit. Quo sit deserunt. Dolorem voluptatem officiis molestiae nihil et voluptate. Sint accusamus quia. Officiis corporis perspiciatis ducimus ullam minus veritatis. Sit aut voluptatem laudantium.", photo_id: 14, user_id: 1},
  {body: "Sapiente sunt libero quo minus quia. Rem quod architecto aut quisquam dicta. Sunt repudiandae dignissimos. Aliquid nihil consequuntur nemo. Expedita et sapiente non enim necessitatibus. Praesentium est earum fugit nihil necessitatibus sit. Occaecati quam ducimus omnis est.", photo_id: 11, user_id: 6},
  {body: "Sit necessitatibus sed sit impedit corporis iusto.", photo_id: 19, user_id: 5},
  {body: "Officiis quam laudantium voluptas voluptas.", photo_id: 2, user_id: 6},
  {body: "Ea iste autem repudiandae rerum ex rerum ut. Et amet vero optio et atque. Illo qui facere amet nihil. Aspernatur omnis voluptas voluptatem et perferendis porro. Et perspiciatis magnam sit similique vel sed rerum. Vitae est qui distinctio. Quia eius saepe quae voluptatem. Deleniti cupiditate atque doloribus id sint. Rerum odit perferendis rerum eos numquam velit. Vitae libero voluptatibus deserunt ipsum. Et rem animi consequatur eum ex quas.", photo_id: 11, user_id: 5},
  {body: "Doloremque error eveniet facere vel id sit voluptas cum sit.", photo_id: 20, user_id: 6},
  {body: "Nisi error beatae.", photo_id: 2, user_id: 3},
  {body: "Natus et asperiores et nisi debitis error.", photo_id: 9, user_id: 4},
  {body: "Voluptatem accusamus illum beatae eos qui. Neque quod velit. Non rerum facere. Officia repellendus voluptatibus non magni aliquam. Sit nihil suscipit totam eum quia. Omnis et facilis enim unde in officiis tenetur.", photo_id: 3, user_id: 4},
  {body: "Eum iusto molestiae repellat et vitae temporibus inventore autem illo.", photo_id: 15, user_id: 1},
  {body: "Rerum laborum tempore. Neque maiores pariatur ipsam. Nihil exercitationem eligendi quo. Beatae at eveniet similique. Et repellat eaque optio ducimus ipsam alias. Dignissimos rerum possimus sapiente aut. Eveniet vero iste doloribus possimus et.", photo_id: 8, user_id: 2},
  {body: "Enim quia ad deserunt esse ducimus sit maxime.", photo_id: 10, user_id: 4},
  {body: "Iure aut est. Sequi natus minima nostrum atque rerum soluta. Minus fugit facere deserunt ea dolores neque. Aliquam et voluptates.", photo_id: 9, user_id: 1},
  {body: "Perspiciatis dolorem expedita saepe vero provident illum modi praesentium officia.", photo_id: 1, user_id: 3},
  {body: "Ut dolore qui consequuntur suscipit. Itaque aut debitis nulla minima aut. Eos velit blanditiis. Ratione aliquam culpa unde officiis. Enim delectus incidunt nemo minima et assumenda. Sit voluptatum ut excepturi aliquid. Et deserunt non suscipit eligendi nemo vel. Non voluptatibus et in expedita repellendus. Reiciendis animi sed in iusto fugiat placeat. Est eligendi expedita dolores.", photo_id: 7, user_id: 6},
  {body: "Ut cum earum ab modi quia doloribus non.", photo_id: 19, user_id: 6},
  {body: "Accusantium rerum ipsum ducimus. Rem aut eligendi praesentium earum omnis debitis mollitia. Laudantium nostrum id nisi. Consequatur ut voluptates iusto. Quasi at aut quia veniam. Similique minima repellat sit quo totam vero minus. Nihil aut nobis velit quasi. Ut in voluptatem corporis. Sit quo est ipsa quas culpa saepe sequi. Sed quibusdam eius quod numquam amet nihil.", photo_id: 5, user_id: 3},
  {body: "Repudiandae in veritatis.", photo_id: 17, user_id: 4},
  {body: "Autem sit praesentium facilis laborum cumque quo earum. Laudantium dolorem et ipsa nam omnis recusandae fuga. Aperiam qui accusamus. Atque ratione libero adipisci et. Reprehenderit qui dolor perferendis ut hic. Blanditiis voluptates cupiditate. At praesentium aut voluptatem consequatur amet et.", photo_id: 13, user_id: 5},
  {body: "Voluptatem est in nam rem aut tempore dolore. Eum blanditiis quisquam facilis facere. Accusantium consequatur occaecati repellat quo itaque. Fuga reiciendis velit commodi aut non earum. Autem ut totam sit maxime nihil. Consectetur et iste voluptatum provident dolores dolores. Dolorem suscipit accusamus libero voluptates quis. Id et quia eos blanditiis sed velit voluptate. Ad vero quaerat necessitatibus omnis sequi expedita. Recusandae sapiente similique unde illo iure commodi cumque.", photo_id: 13, user_id: 2},
  {body: "Et veniam eius quo quia velit molestiae unde. Adipisci et maiores. Et repellat possimus in ut quae.", photo_id: 16, user_id: 1},
  {body: "Saepe dolor excepturi ratione ad animi quia.", photo_id: 5, user_id: 2},
  {body: "Voluptate expedita corporis ut.", photo_id: 14, user_id: 6},
  {body: "Placeat repellendus ut doloremque ullam repellat ut suscipit.", photo_id: 2, user_id: 1},
  {body: "In voluptatem beatae est officia atque veritatis expedita molestias vitae ex dicta facilis.", photo_id: 17, user_id: 1},
  {body: "Sunt dolorum consequatur nobis nesciunt voluptas labore. Quas maiores repudiandae est vero. Numquam modi non iste iure molestias. Ut illo blanditiis beatae aliquid ad dicta impedit. Eveniet iste ut non vel inventore pariatur libero.", photo_id: 6, user_id: 4},
  {body: "Nostrum illum repellat. Non et exercitationem sint. Pariatur eos ut voluptas praesentium blanditiis voluptatem. Minus eaque distinctio qui animi.", photo_id: 2, user_id: 6},
  {body: "Atque deserunt mollitia sit. Quae et repudiandae vel amet. Repellendus expedita recusandae numquam. Inventore iusto est voluptas consequatur enim rem.", photo_id: 20, user_id: 4},
  {body: "Non dolorem consequatur recusandae exercitationem voluptatem. Vel hic sed deserunt cum magnam aut. Eos deserunt velit magni. Et illum quidem. Veritatis eius nobis id eos dolores ratione labore. Amet dolorem optio voluptas sint aspernatur. Qui dolores modi commodi odit voluptas quas. Est rem odit minima. Iusto odio rerum aut similique quo.", photo_id: 5, user_id: 2},
  {body: "Occaecati qui aperiam ut ipsam perferendis.", photo_id: 1, user_id: 5},
  {body: "Similique.", photo_id: 13, user_id: 3},
  {body: "Rerum omnis in. Quo itaque dignissimos aut repellat nulla molestiae. Atque quibusdam dignissimos natus cupiditate ipsa. Quia cum eum sed voluptas est nihil nam. Sunt molestiae aut non aut placeat laudantium. Praesentium cupiditate earum dolor tempora. Error et dolore inventore officia assumenda aut. Illo aliquid harum id qui pariatur quis. Sint adipisci est odio voluptatem.", photo_id: 14, user_id: 2},
  {body: "Maiores et velit debitis vel non.", photo_id: 17, user_id: 4},
  {body: "In suscipit hic neque nostrum illo consectetur culpa asperiores iste ducimus laborum qui quibusdam.", photo_id: 12, user_id: 6},
  {body: "Sed dicta repellendus est mollitia occaecati sunt fugit dolores deleniti delectus hic.", photo_id: 1, user_id: 3},
  {body: "Natus libero qui sint mollitia vitae dolorem laudantium.", photo_id: 5, user_id: 3},
  {body: "Perspiciatis optio quidem incidunt non. Id omnis aliquam saepe reiciendis. Necessitatibus aut quaerat nihil est sunt ducimus. Cum unde blanditiis qui. Adipisci sit quod. Vero error et.", photo_id: 7, user_id: 1},
  {body: "Sed nesciunt aliquam est quas. Itaque optio provident et sed vel est modi. Laudantium sint ea. Suscipit alias dolore ratione tenetur. Voluptate assumenda qui nostrum quibusdam. Officia est laborum quia dolores. Voluptatem error accusantium. Vel sunt officia. In pariatur ducimus.", photo_id: 6, user_id: 3},
  {body: "Quod laborum inventore fugiat. Numquam voluptatum molestias excepturi. Et in ducimus quia non. Dignissimos aut et id maxime. Fugit dolores nulla rem voluptatem. Exercitationem laboriosam adipisci placeat et ipsam.", photo_id: 15, user_id: 1},
  {body: "Quos esse et doloribus at aliquam id architecto odio recusandae omnis.", photo_id: 10, user_id: 6},
  {body: "Rerum voluptatem voluptatem. Eaque eligendi itaque iure exercitationem sint deleniti aliquid. Illo dolorem in veritatis qui reprehenderit. Nostrum maiores nam neque velit optio molestiae.", photo_id: 17, user_id: 6},
  {body: "Quia tempore est inventore dolor autem totam saepe. Unde voluptas quo harum. Eum corporis et perferendis sit quia vero sed. Sed iste iusto error saepe quibusdam. Dolorem totam omnis voluptatem numquam beatae error. Dolor ex quo magnam voluptatibus error labore. Et sequi odit fugit laudantium non sed vel. Explicabo quia et asperiores omnis aperiam error possimus. Nesciunt repellendus aut sunt hic. Dolores eveniet dolor excepturi amet sint.", photo_id: 12, user_id: 5},
  {body: "Vitae itaque voluptates soluta est autem et nihil.", photo_id: 4, user_id: 3},
  {body: "Enim cum consequatur sit dolor officia.", photo_id: 19, user_id: 5},
  {body: "Sint aut nam. Quia ullam labore quis. Et temporibus qui vero et. Ut labore quae quia sit adipisci culpa. Qui libero temporibus sunt ducimus modi laboriosam aut. Vel nobis laudantium esse magnam hic est iusto. Quia esse aut ea. In omnis dolores enim natus veritatis distinctio est.", photo_id: 1, user_id: 2},
  {body: "Voluptatem occaecati accusantium rerum neque nam.", photo_id: 4, user_id: 3},
  {body: "Suscipit aut tempore molestiae odit voluptas quod perspiciatis.", photo_id: 10, user_id: 6},
  {body: "Ut fuga quam cum debitis doloremque assumenda voluptas saepe voluptas ratione velit.", photo_id: 1, user_id: 3},
  {body: "Quia sit harum sequi voluptatem. Ipsa est est nam modi voluptatem.", photo_id: 7, user_id: 2},
  {body: "Ut incidunt qui est maiores. Fugit asperiores at sapiente impedit. Deserunt magni eaque amet quo inventore eos. Sit minima iusto ea culpa quo. Rem commodi dolorem. Autem tempora mollitia reprehenderit esse cum earum ex.", photo_id: 4, user_id: 1},
  {body: "Illum doloribus in recusandae veniam nihil error rerum maxime nobis.", photo_id: 15, user_id: 2},
  {body: "Eos ea qui asperiores ut qui veritatis dignissimos.", photo_id: 2, user_id: 4},
  {body: "Occaecati adipisci molestiae corrupti ut repellendus enim dolorem dolor omnis vero.", photo_id: 16, user_id: 2},
  {body: "Et.", photo_id: 18, user_id: 3},
  {body: "Sunt quae natus. Ut reprehenderit alias. Velit praesentium placeat molestiae ea qui id vel. Cum aut laudantium provident eum voluptates vel. Ut nulla repellendus. Ut quaerat eum occaecati id animi. Nulla nobis et placeat cum laborum sed. Facere doloremque qui qui. Et nam natus doloribus aut eum nisi aspernatur. Est qui tempore. Et quia minima ut.", photo_id: 18, user_id: 2},
  {body: "Est quia cum eos quam pariatur. Porro officiis autem aliquid labore quia ullam voluptates.", photo_id: 19, user_id: 3},
  {body: "Consequatur placeat vitae delectus odit est et perspiciatis amet dignissimos nulla reprehenderit similique molestias.", photo_id: 10, user_id: 4},
  {body: "Consectetur voluptatem laudantium. Adipisci quo sint provident. Illo aut ab ad. Tempore nostrum odit molestias repellendus architecto fuga. Tenetur deleniti quisquam eum incidunt sit. Aut vitae molestiae corrupti illo fugiat.", photo_id: 10, user_id: 1},
  {body: "Eum dolorum sequi veritatis fuga et ullam minus.", photo_id: 18, user_id: 2},
  {body: "Id nostrum mollitia aut exercitationem. Rem eos laudantium. Perspiciatis incidunt neque dolores eos provident at. Omnis et nihil fugit. Cum vero saepe quisquam sit quibusdam et.", photo_id: 11, user_id: 6},
  {body: "Est debitis.", photo_id: 7, user_id: 4},
  {body: "Praesentium omnis molestiae est mollitia maxime. Ut libero soluta temporibus sit minus aut natus. Deserunt eos recusandae dolor optio sint. Et delectus quam sunt sed consectetur neque minima. Consequatur earum quas est. Earum impedit dolores enim. Cupiditate cum minima saepe at magnam.", photo_id: 11, user_id: 1},
  {body: "Et maiores quam officiis deleniti quia dolor. Distinctio officiis numquam cupiditate et est. Eos enim modi temporibus ipsum qui dolor et. Enim est corrupti aut et est quia. Aut quas itaque saepe dolores.", photo_id: 2, user_id: 2},
  {body: "Nemo voluptatem praesentium alias provident laborum.", photo_id: 9, user_id: 2},
  {body: "Qui dolores magni minima cum. Nostrum quisquam voluptatem quos provident voluptatibus enim. Suscipit ut molestiae a enim facere aut. Praesentium illum dolor voluptatem beatae sit. Magni qui et placeat similique. Consequatur itaque reprehenderit deleniti dolorem repellat expedita quibusdam. Rerum ipsum adipisci est. Totam sapiente numquam nihil qui. Provident dolores deserunt doloremque qui.", photo_id: 7, user_id: 2},
  {body: "A tempora eligendi modi sapiente ratione ad voluptatum labore.", photo_id: 1, user_id: 1},
  {body: "Illum rem et nobis nam consequuntur eius sapiente. Nisi rerum in quos architecto magni. Ea corporis aut. Laboriosam totam veritatis ea aut architecto. Esse non ipsam excepturi. Vitae autem dolore voluptatibus. Eos harum velit voluptate possimus. Ratione omnis nam ea voluptatem illum quia.", photo_id: 8, user_id: 3},
  {body: "Pariatur earum ducimus omnis magni reprehenderit dolor. Et aut reiciendis ut et molestiae labore ipsum. Adipisci omnis debitis.", photo_id: 9, user_id: 5},
  {body: "Accusamus est id autem voluptatem consectetur sequi nihil dolorem dolore officiis facilis ipsum.", photo_id: 9, user_id: 1},
  {body: "Totam eos voluptatum quo ex. Voluptas consequatur nisi perferendis. Sed sed quis non et nisi. Praesentium eligendi voluptate perspiciatis aliquid voluptas quidem omnis. Adipisci dolor alias et dolorum itaque aut. Qui est quis itaque.", photo_id: 1, user_id: 6},
  {body: "Quaerat quis sequi deserunt sed quia et.", photo_id: 1, user_id: 3},
  {body: "Optio atque pariatur aut non perferendis id. Dolorem consequatur nisi et qui itaque non aliquid. Exercitationem omnis id voluptatem illo. Officiis explicabo voluptate sit modi neque mollitia veritatis.", photo_id: 9, user_id: 3},
  {body: "Fugiat similique neque saepe aut quis sapiente.", photo_id: 13, user_id: 1},
  {body: "Distinctio quod neque. Distinctio aliquid officia soluta cum modi. Sed sed sequi. Sed sit possimus velit neque officia non veritatis. Aut sint dolorum voluptas facere. Illo inventore assumenda. Excepturi rem cupiditate distinctio fugiat quia alias. Voluptas incidunt fuga rem.", photo_id: 2, user_id: 2},
  {body: "Illo rem quasi occaecati et quas quis reiciendis. Consectetur veniam quia. Et consectetur sed voluptatem ut minus. Quo blanditiis voluptatibus aliquam fuga. Architecto et perspiciatis sequi dolores. Impedit aut quisquam molestias at officia. Sit dolore rerum.", photo_id: 18, user_id: 2},
  {body: "Ipsam fugit harum labore tempore facilis adipisci. Et distinctio ut hic. Nisi harum nesciunt dolorum repudiandae. Aut quos perspiciatis deserunt fugit a temporibus. Alias praesentium quam ab pariatur dolores. Sit rerum nemo reiciendis voluptas. Rerum aut consequatur sit quidem. Dolore non qui repellat molestiae. Et vel laborum illum qui eum.", photo_id: 7, user_id: 1},
  {body: "Magni et dolorum modi. Ut tenetur et numquam. Id modi voluptates facere dolor at odit occaecati. Itaque consectetur dignissimos dolore molestias vel enim ullam. Ut aliquam expedita dignissimos laboriosam. Velit illum necessitatibus nihil porro et corporis excepturi. Rerum culpa consequuntur corporis non consequatur repudiandae sequi. Dolores laboriosam et quibusdam ipsam. Quia consequuntur voluptatem nemo ipsa placeat. Rerum aut deleniti consequatur.", photo_id: 12, user_id: 6},
  {body: "Magnam ut sed saepe inventore sunt. Repudiandae officia impedit et odit aperiam. Voluptas fuga tempore laborum esse. Eum autem et velit non non quae ipsam. Sunt autem et soluta consequuntur sed. Harum ut quisquam. Non voluptates dolores blanditiis voluptatem assumenda. Velit omnis facilis error. Earum tempore numquam praesentium soluta nobis vitae saepe. Beatae nihil nesciunt distinctio amet. Enim sit quibusdam rem eum incidunt id.", photo_id: 3, user_id: 1},
  {body: "Dolorum voluptas voluptate assumenda quisquam facilis corporis. Minima sunt deserunt enim sequi ad blanditiis nihil. Accusamus dolorem nihil eum quis atque. Nam dicta consectetur. Est accusamus est. Dolorem qui eligendi velit quas. Velit facere maiores quasi dolorem. Eum et enim nemo consectetur. Occaecati perferendis voluptatem natus consequatur sunt omnis quo. Id est tempora dolore nisi ea rerum odio. Possimus ipsam repudiandae qui sed eos voluptas optio. Consequatur ducimus vel sequi voluptatem tempore nam error.", photo_id: 15, user_id: 1},
  {body: "Id sint similique eaque impedit omnis veritatis ut voluptate porro.", photo_id: 11, user_id: 4},
  {body: "Minus mollitia est eos voluptate ut. Nihil exercitationem deleniti omnis. Alias ullam non placeat. Rerum non minus repellendus sit perferendis numquam. Totam ut sed voluptatibus est facilis dolorum. At nihil dolor natus iusto consequuntur sit. Nulla sint dignissimos debitis omnis corrupti voluptas. Et nostrum eos consectetur amet aut dolore reprehenderit. Et quas suscipit sapiente. Necessitatibus excepturi non suscipit ut sint quo cupiditate. Necessitatibus quae eos ipsa ad voluptatum perspiciatis vel.", photo_id: 1, user_id: 3},
  {body: "Sed iure ut quia architecto veritatis. Amet fugit doloremque dolorem beatae eius neque veritatis. Quidem facilis voluptate aspernatur ullam blanditiis quia quia.", photo_id: 16, user_id: 3},
  {body: "Aliquid sit pariatur assumenda corporis quis. Repellat sed rem. Dolor ut fugit tenetur. Voluptas quia voluptas ab.", photo_id: 7, user_id: 5},
  {body: "Libero reprehenderit expedita harum accusamus est ut ducimus.", photo_id: 14, user_id: 4},
  {body: "glarg glarg glarging", photo_id: 69, user_id: 7},
  {body: "sdafds", photo_id: 57, user_id: 7},
  {body: "fsadfasfew", photo_id: 57, user_id: 7},
  {body: "sdafew", photo_id: 57, user_id: 7},
  {body: "fewffdsadc", photo_id: 57, user_id: 7},
  {body: "fsw3dsafe", photo_id: 57, user_id: 7},
  {body: "dfasdfasdf", photo_id: 57, user_id: 7},
  {body: "fsasdfew", photo_id: 57, user_id: 7},
  {body: "dsfaewds", photo_id: 57, user_id: 7},
  {body: "tregfdg", photo_id: 57, user_id: 7},
  {body: "dsfaewdc", photo_id: 57, user_id: 7},
  {body: "dfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewrdfsadsfadsfewr", photo_id: 57, user_id: 7},
  {body: "sdfaecae", photo_id: 4, user_id: 7},
  {body: "dsafew", photo_id: 59, user_id: 7},
  {body: "sadfedasf", photo_id: 55, user_id: 7},
  {body: "dsfadf", photo_id: 55, user_id: 7},
  {body: "sdafdsf", photo_id: 61, user_id: 7},
  {body: "dsfaeqwx", photo_id: 61, user_id: 7},
  {body: "we ow wow ee woo", photo_id: 64, user_id: 1},
  {body: "sdaff fae", photo_id: 64, user_id: 1},
  {body: "so snow woo", photo_id: 70, user_id: 1},
  {body: "sdfasfd", photo_id: 69, user_id: 1},
  {body: "dsafsd", photo_id: 62, user_id: 1},
  {body: "sdafewfads", photo_id: 56, user_id: 1},
  {body: "dasfewdaf", photo_id: 58, user_id: 1},
  {body: "well said tad... well said", photo_id: 62, user_id: 7},
  {body: "dsfaewf", photo_id: 2, user_id: 7},
  {body: "sdfasef", photo_id: 2, user_id: 7},
  {body: "sdafewf", photo_id: 2, user_id: 7}
])
Photo.create!([
  {title: "Pinecones?", description: "LOOK AT ALL THESE PINECONES\n\n", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506907/wmmx2oytrz9jwmet3of9.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506907/wmmx2oytrz9jwmet3of9.jpg", albuming_id: nil, filters: nil},
  {title: "rock'n'water", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506888/ykqqkl5b9lpcg7f1p123.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506888/ykqqkl5b9lpcg7f1p123.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506899/ryvjpmi2jdoebe3iplem.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506899/ryvjpmi2jdoebe3iplem.jpg", albuming_id: nil, filters: nil},
  {title: "orange suns", description: "ffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfadsffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsf\nsdffasd\ndasf\nsd\nf\nsadf\nadsf", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506875/yxfllichvbv8jugyzjun.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506875/yxfllichvbv8jugyzjun.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567961/cssobc2vv70018maceaq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567961/cssobc2vv70018maceaq.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568036/zr5tzul9vzw9qvetdpmr.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568036/zr5tzul9vzw9qvetdpmr.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568056/ducry4tleg8cfu8kex5d.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568056/ducry4tleg8cfu8kex5d.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568087/utklb2jvbzrv2h7yqfu8.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568087/utklb2jvbzrv2h7yqfu8.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568237/odfrapicgjbhb0zhwljz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568237/odfrapicgjbhb0zhwljz.jpg", albuming_id: nil, filters: nil},
  {title: "Water and Rocks", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568278/xy6asygjymlq9lz5wgw3.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568278/xy6asygjymlq9lz5wgw3.jpg", albuming_id: nil, filters: nil},
  {title: "clouds", description: "I think I can see a mountain too", user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568270/ms1ongsmyamdlfhinnrq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568270/ms1ongsmyamdlfhinnrq.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573475/is6kkgv0orro0lccovcw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573475/is6kkgv0orro0lccovcw.jpg", albuming_id: nil, filters: nil},
  {title: "Orange and Blue", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568248/o4qderewgojwvrmcpqkg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568248/o4qderewgojwvrmcpqkg.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573489/gtzvqznidaqc2yawlk8m.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573489/gtzvqznidaqc2yawlk8m.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506919/yak37eq3lovk5fbkn1lk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506919/yak37eq3lovk5fbkn1lk.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567919/rr9mm2o6q5cijgvakkto.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567919/rr9mm2o6q5cijgvakkto.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568077/bl3vqs2uuprcz75n3zws.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568077/bl3vqs2uuprcz75n3zws.jpg", albuming_id: nil, filters: nil},
  {title: "Looks dangerous", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567885/ulatmcr1kywbu8xgo0sy.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567885/ulatmcr1kywbu8xgo0sy.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "la la lalalala", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567834/lvxofvho8isvepume05z.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567834/lvxofvho8isvepume05z.jpg", albuming_id: nil, filters: nil},
  {title: "Fall", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567861/l1ncijpv7sn0zrordllc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567861/l1ncijpv7sn0zrordllc.jpg", albuming_id: nil, filters: nil},
  {title: "Majestic Alcoholism", description: "sadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efj", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg", albuming_id: nil, filters: nil},
  {title: "title", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567844/svpzafqwropjoi15izpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567844/svpzafqwropjoi15izpa.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "\n\n\n\n\n\n\n\n\n", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567910/f1vzfg466cxtajwseabi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567910/f1vzfg466cxtajwseabi.jpg", albuming_id: nil, filters: nil},
  {title: "Green door", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567997/dypwznqr7fvfj78npmlx.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567997/dypwznqr7fvfj78npmlx.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "sdfasdf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568101/vki57g6ymn0jarzvrpec.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568101/vki57g6ymn0jarzvrpec.jpg", albuming_id: nil, filters: nil},
  {title: "sadf", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567901/ll0eautrhzidevgj26xi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567901/ll0eautrhzidevgj26xi.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568024/avooyw2bbeu3lrdftmjw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568024/avooyw2bbeu3lrdftmjw.jpg", albuming_id: nil, filters: nil},
  {title: "beans", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567949/wueevxjcfhauuumyfptl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567949/wueevxjcfhauuumyfptl.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567892/c368dobi8dr0u27mgbv1.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567892/c368dobi8dr0u27mgbv1.jpg", albuming_id: nil, filters: nil},
  {title: "lotta tan in this one", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567932/nd3hexzkdorjn7eieawk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567932/nd3hexzkdorjn7eieawk.jpg", albuming_id: nil, filters: nil},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568069/gtpham7dmmlwqlzobnqc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568069/gtpham7dmmlwqlzobnqc.jpg", albuming_id: nil, filters: nil},
  {title: "dsaf", description: "fdsaf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567941/srm6g452ouksm2mumm21.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567941/srm6g452ouksm2mumm21.jpg", albuming_id: nil, filters: nil},
  {title: "telebooth", description: "a booth in the glow of night", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567975/nsqubkstwvcchrskrbpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567975/nsqubkstwvcchrskrbpa.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573497/zpi6hkmyzcymqf9jncuf.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573497/zpi6hkmyzcymqf9jncuf.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573514/ysuovu1a1zti7ihmdght.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573514/ysuovu1a1zti7ihmdght.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573525/ub1ki1j7gol3hprbrjil.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573525/ub1ki1j7gol3hprbrjil.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573537/pdghysdo5pw7w3k6vc8n.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573537/pdghysdo5pw7w3k6vc8n.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573588/eb1tywyi75penp8wpxvl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573588/eb1tywyi75penp8wpxvl.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573596/gpby0lpg0ye1blo7swi2.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573596/gpby0lpg0ye1blo7swi2.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573603/kn5wvqby9agcei0zdf7q.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573603/kn5wvqby9agcei0zdf7q.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573610/leafneiwhzjt3fvgwtpt.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573610/leafneiwhzjt3fvgwtpt.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573616/igmmo21gfwskhpq15k4s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573616/igmmo21gfwskhpq15k4s.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573624/thy8geqji8zbgzoui0vu.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573624/thy8geqji8zbgzoui0vu.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573635/mcznlokr7uoyxvu3k22f.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573635/mcznlokr7uoyxvu3k22f.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573659/pae3qn6ccqcqg0tqqsol.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573659/pae3qn6ccqcqg0tqqsol.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573673/ippwqlanpolrrgrkobev.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573673/ippwqlanpolrrgrkobev.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573703/gps7xunnmxodtof5xtds.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573703/gps7xunnmxodtof5xtds.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567825/hbssjxxwoffneuedeysp.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567825/hbssjxxwoffneuedeysp.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 6, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439597776/iomxelfkvjzoilrd0gxg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439597776/iomxelfkvjzoilrd0gxg.jpg", albuming_id: nil, filters: nil},
  {title: "wow", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704558/chhcdlqqatqvqtdgxqaj.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704558/chhcdlqqatqvqtdgxqaj.jpg", albuming_id: nil, filters: nil},
  {title: "I'm getting dizzy", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439739084/yfrypm7cgvh9cd2h82og.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439739084/yfrypm7cgvh9cd2h82og.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704520/tdqh0j1gm0alz6eei8kq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704520/tdqh0j1gm0alz6eei8kq.jpg", albuming_id: nil, filters: nil},
  {title: "", description: "", user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704574/yf7btz05nl7lubjf5xmi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704574/yf7btz05nl7lubjf5xmi.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738328/enc058emzzpbu8fre0nh.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738328/enc058emzzpbu8fre0nh.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738386/myr5w9imlerideugcnj0.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738386/myr5w9imlerideugcnj0.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439738668/xiakkntdydqbntyal52f.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439738668/xiakkntdydqbntyal52f.jpg", albuming_id: nil, filters: nil},
  {title: "what a good book!", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439704542/vkr58kvpf988lgplkdxz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439704542/vkr58kvpf988lgplkdxz.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786041/ovavwg7x95tfszdcctjz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786041/ovavwg7x95tfszdcctjz.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786409/ichxszoarur7wdzmu6cx.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786409/ichxszoarur7wdzmu6cx.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439789405/ch1o3v2iwdrmrqshxu2m.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439789405/ch1o3v2iwdrmrqshxu2m.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568069/gtpham7dmmlwqlzobnqc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568069/gtpham7dmmlwqlzobnqc.jpg", albuming_id: nil, filters: "{\"bl\":1,\"br\":82,\"co\":200,\"gr\":44,\"hu\":315,\"iv\":0,\"sa\":100,\"se\":0}"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1440032536/jposxhrrldo7hfnc07jl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1440032536/jposxhrrldo7hfnc07jl.jpg", albuming_id: nil, filters: "{\"bl\":0,\"br\":139,\"co\":100,\"gr\":0,\"hu\":4,\"iv\":0,\"sa\":100,\"se\":70}"},
  {title: ":(", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439786899/ijzxbxh0ahkf3atyypbw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439786899/ijzxbxh0ahkf3atyypbw.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: "white water rafting yo", user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439787412/u0yqdoemoly5ah0ijg1j.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439787412/u0yqdoemoly5ah0ijg1j.jpg", albuming_id: nil, filters: nil},
  {title: "island paradise", description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1440032536/jposxhrrldo7hfnc07jl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1440032536/jposxhrrldo7hfnc07jl.jpg", albuming_id: nil, filters: nil},
  {title: nil, description: nil, user_id: 7, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439787363/bddc59vjalhxpwpoppzy.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439787363/bddc59vjalhxpwpoppzy.jpg", albuming_id: nil, filters: "{\"bl\":0,\"br\":100,\"co\":100,\"gr\":0,\"hu\":0,\"iv\":0,\"sa\":100,\"se\":0}"}
])
User.create!([
  {username: "tad", password_digest: "$2a$10$fUGJM1ZkRi61qZDpGRjmEeVEsZeIulEtF13F1OE1Z25HTz4tGJ4d2", session_token: "PbxUEg3OcH5bV3YsyPsOZg"},
  {username: "pointlessComments", password_digest: "$2a$10$d4Y9l6EVq0ct0VYywJstseTyUR8fOvwB.xSxl6ks1Uuci1DNJNyQe", session_token: "IOOmbticQ3M5e0zknA9ldw"},
  {username: "i_love_pictur", password_digest: "$2a$10$WI5kuxQ0tXS9Si2vHYrW.enpoXVtkxP/j91yxCpr.km51EuW5iNtO", session_token: "rseP2ZfOyXou9UhV7TgGjQ"},
  {username: "photo4lyfe", password_digest: "$2a$10$IJu8GpoGrG5kr8b88yKxm.0blFSV3wLeIq2Dxue/5BBS//anIvxaC", session_token: "evXk6caoTEgl8RtBrH5qkA"},
  {username: "anewuser", password_digest: "$2a$10$bsT3Szp212hhcAMa.8PNX.avY3bWGvuNlIzigozGNEkRRM7W.NGw6", session_token: "vgtnG2GkfdsMI1ISHKi_fw"},
  {username: "test", password_digest: "$2a$10$Y5kConGq8nFsimVYe9XTAunmxdK2Htetpctz8iAnUa0/FPIE6kyyq", session_token: "aQPljq6hsHunAGiCBEXhvg"},
  {username: "guest", password_digest: "$2a$10$dHHLYl8fA/6hLHt/xaAh6eOQ9JRCE7N2J9XQpP6yjZ3hMcLrQfd5m", session_token: "vGKpJS2ROouFGb7tvCItDg"}
  {username: "inactive_user", password_digest: "$2a$10$j6EtiYgaAYYDralGUnIsguTiHMpGiEka28xRyfNdD4z3Br/em0D9a", session_token: "Xj2kXWeLvdKWJwJY_Y9VGQ"},
])
Voting.create!([
  {user_id: 1, photo_id: 1, score: 1},
  {user_id: 2, photo_id: 1, score: 1},
  {user_id: 3, photo_id: 1, score: 1},
  {user_id: 4, photo_id: 1, score: 1},
  {user_id: 5, photo_id: 1, score: 1},
  {user_id: 6, photo_id: 1, score: 1},
  {user_id: 8, photo_id: 1, score: 1},
  {user_id: 7, photo_id: 3, score: 1},
  {user_id: 7, photo_id: 10, score: 1},
  {user_id: 7, photo_id: 14, score: 1},
  {user_id: 7, photo_id: 9, score: 1},
  {user_id: 7, photo_id: 1, score: 1},
  {user_id: 7, photo_id: 7, score: 1},
  {user_id: 7, photo_id: 67, score: 1},
  {user_id: 7, photo_id: 36, score: 1},
  {user_id: 7, photo_id: 60, score: 1},
  {user_id: 7, photo_id: 2, score: 1},
  {user_id: 7, photo_id: 70, score: 1},
  {user_id: 7, photo_id: 69, score: 1},
  {user_id: 7, photo_id: 68, score: 1},
  {user_id: 7, photo_id: 4, score: 1},
  {user_id: 7, photo_id: 55, score: 1},
  {user_id: 7, photo_id: 91, score: 1},
  {user_id: 7, photo_id: 22, score: 1},
  {user_id: 7, photo_id: 42, score: 1},
  {user_id: 1, photo_id: 99, score: 1},
  {user_id: 1, photo_id: 91, score: 1},
  {user_id: 1, photo_id: 70, score: 1},
  {user_id: 7, photo_id: 62, score: 1},
  {user_id: 7, photo_id: 53, score: 1}
])
