Comment.create!([
  {body: "this is a long comment so I can see hwo long a comment is to see how much space it takes up to know how to style the page so as to fit all the content but also look decent where there is not a lot of content", photo_id: 49, user_id: 1, username: "tad"},
  {body: "test comment 1", photo_id: 49, user_id: 1, username: "tad"}
])
Photo.create!([
  {title: "Pinecones?", description: "LOOK AT ALL THESE PINECONES\n\n", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506907/wmmx2oytrz9jwmet3of9.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506907/wmmx2oytrz9jwmet3of9.jpg"},
  {title: "rock'n'water", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506888/ykqqkl5b9lpcg7f1p123.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506888/ykqqkl5b9lpcg7f1p123.jpg"},
  {title: "", description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506899/ryvjpmi2jdoebe3iplem.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506899/ryvjpmi2jdoebe3iplem.jpg"},
  {title: "orange suns", description: "ffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfadsffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsfffdsaf f e  fwjiq eijf  f wer iwefq  fwej  fjwe ffjq jewqfweqf sdsadfasdfsadfdfdsfdsfsdafdf fsaf        f\nsdfads\nsdffasd\ndasf\nsd\nf\nsadf\nadsf\nsdffasd\ndasf\nsd\nf\nsadf\nadsf", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506875/yxfllichvbv8jugyzjun.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506875/yxfllichvbv8jugyzjun.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567961/cssobc2vv70018maceaq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567961/cssobc2vv70018maceaq.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568036/zr5tzul9vzw9qvetdpmr.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568036/zr5tzul9vzw9qvetdpmr.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568042/ypalqcwmuhfhh0fzi1fa.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568056/ducry4tleg8cfu8kex5d.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568056/ducry4tleg8cfu8kex5d.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568087/utklb2jvbzrv2h7yqfu8.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568087/utklb2jvbzrv2h7yqfu8.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568237/odfrapicgjbhb0zhwljz.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568237/odfrapicgjbhb0zhwljz.jpg"},
  {title: "Water and Rocks", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568278/xy6asygjymlq9lz5wgw3.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568278/xy6asygjymlq9lz5wgw3.jpg"},
  {title: "clouds", description: "I think I can see a mountain too", user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568270/ms1ongsmyamdlfhinnrq.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568270/ms1ongsmyamdlfhinnrq.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573475/is6kkgv0orro0lccovcw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573475/is6kkgv0orro0lccovcw.jpg"},
  {title: "Orange and Blue", description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568248/o4qderewgojwvrmcpqkg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568248/o4qderewgojwvrmcpqkg.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573489/gtzvqznidaqc2yawlk8m.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573489/gtzvqznidaqc2yawlk8m.jpg"},
  {title: nil, description: "", user_id: 2, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439506919/yak37eq3lovk5fbkn1lk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439506919/yak37eq3lovk5fbkn1lk.jpg"},
  {title: "", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567919/rr9mm2o6q5cijgvakkto.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567919/rr9mm2o6q5cijgvakkto.jpg"},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568077/bl3vqs2uuprcz75n3zws.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568077/bl3vqs2uuprcz75n3zws.jpg"},
  {title: "Looks dangerous", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567885/ulatmcr1kywbu8xgo0sy.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567885/ulatmcr1kywbu8xgo0sy.jpg"},
  {title: "", description: "la la lalalala", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567834/lvxofvho8isvepume05z.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567834/lvxofvho8isvepume05z.jpg"},
  {title: "Fall", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567861/l1ncijpv7sn0zrordllc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567861/l1ncijpv7sn0zrordllc.jpg"},
  {title: "Majestic Alcoholism", description: "sadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efjsadfdf s\nsdaf f safasd fsad;f sadfj a;sf a;ejsf w iejfj  a ;fdjj aewf;o efj", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439532033/b9vnzsv4jtxwnecfwr3s.jpg"},
  {title: "title", description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567844/svpzafqwropjoi15izpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567844/svpzafqwropjoi15izpa.jpg"},
  {title: "", description: "\n\n\n\n\n\n\n\n\n", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567910/f1vzfg466cxtajwseabi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567910/f1vzfg466cxtajwseabi.jpg"},
  {title: "Green door", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567997/dypwznqr7fvfj78npmlx.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567997/dypwznqr7fvfj78npmlx.jpg"},
  {title: nil, description: "sdfasdf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568101/vki57g6ymn0jarzvrpec.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568101/vki57g6ymn0jarzvrpec.jpg"},
  {title: "sadf", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567901/ll0eautrhzidevgj26xi.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567901/ll0eautrhzidevgj26xi.jpg"},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568024/avooyw2bbeu3lrdftmjw.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568024/avooyw2bbeu3lrdftmjw.jpg"},
  {title: "beans", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567949/wueevxjcfhauuumyfptl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567949/wueevxjcfhauuumyfptl.jpg"},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567892/c368dobi8dr0u27mgbv1.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567892/c368dobi8dr0u27mgbv1.jpg"},
  {title: "lotta tan in this one", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567932/nd3hexzkdorjn7eieawk.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567932/nd3hexzkdorjn7eieawk.jpg"},
  {title: "", description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439568069/gtpham7dmmlwqlzobnqc.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439568069/gtpham7dmmlwqlzobnqc.jpg"},
  {title: "dsaf", description: "fdsaf", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567941/srm6g452ouksm2mumm21.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567941/srm6g452ouksm2mumm21.jpg"},
  {title: "telebooth", description: "a booth in the glow of night", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567975/nsqubkstwvcchrskrbpa.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567975/nsqubkstwvcchrskrbpa.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573497/zpi6hkmyzcymqf9jncuf.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573497/zpi6hkmyzcymqf9jncuf.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573506/vsqaz9gmdpgpqn37i3ae.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573514/ysuovu1a1zti7ihmdght.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573514/ysuovu1a1zti7ihmdght.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573525/ub1ki1j7gol3hprbrjil.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573525/ub1ki1j7gol3hprbrjil.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573537/pdghysdo5pw7w3k6vc8n.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573537/pdghysdo5pw7w3k6vc8n.jpg"},
  {title: nil, description: nil, user_id: 3, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573560/akj3dui61yy9ayioksvh.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573560/akj3dui61yy9ayioksvh.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573588/eb1tywyi75penp8wpxvl.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573588/eb1tywyi75penp8wpxvl.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573596/gpby0lpg0ye1blo7swi2.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573596/gpby0lpg0ye1blo7swi2.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573603/kn5wvqby9agcei0zdf7q.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573603/kn5wvqby9agcei0zdf7q.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573610/leafneiwhzjt3fvgwtpt.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573610/leafneiwhzjt3fvgwtpt.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573616/igmmo21gfwskhpq15k4s.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573616/igmmo21gfwskhpq15k4s.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573624/thy8geqji8zbgzoui0vu.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573624/thy8geqji8zbgzoui0vu.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573635/mcznlokr7uoyxvu3k22f.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573635/mcznlokr7uoyxvu3k22f.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573659/pae3qn6ccqcqg0tqqsol.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573659/pae3qn6ccqcqg0tqqsol.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573673/ippwqlanpolrrgrkobev.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573673/ippwqlanpolrrgrkobev.jpg"},
  {title: nil, description: nil, user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439573703/gps7xunnmxodtof5xtds.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439573703/gps7xunnmxodtof5xtds.jpg"},
  {title: nil, description: "", user_id: 1, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439567825/hbssjxxwoffneuedeysp.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439567825/hbssjxxwoffneuedeysp.jpg"},
  {title: "", description: "", user_id: 6, url: "http://res.cloudinary.com/dmiidzjtl/image/upload/v1439597776/iomxelfkvjzoilrd0gxg.jpg", thumb_url: "http://res.cloudinary.com/dmiidzjtl/image/upload/c_scale,w_400/v1439597776/iomxelfkvjzoilrd0gxg.jpg"}
])
User.create!([
  {username: "anewuser", password_digest: "$2a$10$bsT3Szp212hhcAMa.8PNX.avY3bWGvuNlIzigozGNEkRRM7W.NGw6", session_token: "O7scfrGYCD5ktfHiZzeSkA"},
  {username: "fdsfasfs", password_digest: "$2a$10$WI5kuxQ0tXS9Si2vHYrW.enpoXVtkxP/j91yxCpr.km51EuW5iNtO", session_token: "rseP2ZfOyXou9UhV7TgGjQ"},
  {username: "photo4lyfe", password_digest: "$2a$10$IJu8GpoGrG5kr8b88yKxm.0blFSV3wLeIq2Dxue/5BBS//anIvxaC", session_token: "0zI_VwLTz24fIp7S1F5HcQ"},
  {username: "newUser", password_digest: "$2a$10$d4Y9l6EVq0ct0VYywJstseTyUR8fOvwB.xSxl6ks1Uuci1DNJNyQe", session_token: "IOOmbticQ3M5e0zknA9ldw"},
  {username: "tad", password_digest: "$2a$10$fUGJM1ZkRi61qZDpGRjmEeVEsZeIulEtF13F1OE1Z25HTz4tGJ4d2", session_token: "IEq7j9j6fmzwVwDZEqxppw"},
  {username: "test", password_digest: "$2a$10$Y5kConGq8nFsimVYe9XTAunmxdK2Htetpctz8iAnUa0/FPIE6kyyq", session_token: "h3RJAumqJjc6vhVY72RsEw"}
])

def body
  rand(2) == 0 ? Faker::Lorem.paragraph(length) : Faker::Lorem.sentence(length)
end

def user
  u = User.find(rand(6) + 1)
  [u.id, u.username]
end

100.times do
  u = user
  Photo.find(rand(20) + 1).comment.create(body: body(5), user_id: u[0], username: u[1])
end
